### ISSUE TITLE
Request: Ability to use items to level up your town

### ISSUE THREAD

**Issue by FireML** [WiIIiam278/HuskTowns#434]
I would like to request the feature to add an item requirement in order to level up a town. The thought is to add a material into the configurations along with the amount needed, which will require players to deposit that amount of the material in order to level up their town.

Here is a config example:
```
level_requirements:
  '1': 
  - money: 2000.0
  '2': 
  - money: 4000.0
  - stone: 64
  - honey_block: 10
  - obsidian: 32
```
